In [1]:
import pandas as pd
import numpy as np

In [2]:


class Perceptron:
    def __init__(self):
        self.weights = None
        self.bias = 0
        
    def initialize(self,n_features):
        self.weights = np.zeros(n_features)
        self.bias = 0
        return
    
    def predict(self,inputs):
        activation = np.dot(inputs, self.weights) + self.bias
        return 1 if activation > 0 else 0
    
    def train(self, X, y, epochs=100, learning_rate=0.1):
        self.initialize(X.shape[1])
        for epoch in range(epochs):
            for inputs, label in zip(X,y):
                y_pred = self.predict(inputs)
                error = label - y_pred
                self.weights += learning_rate * error * inputs
                self.bias += learning_rate * error
        return

X_train = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
y_train = np.array([0, 0, 0, 1])

p = Perceptron()
p.train(X_train, y_train, epochs=100, learning_rate=0.1)
test_input = np.array([0, 0])
print(p.predict(test_input))  # Output: 0

# OR
X_train = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
y_train = np.array([0, 1, 1, 1])

p = Perceptron()
p.train(X_train, y_train, epochs=100, learning_rate=0.1)
test_input = np.array([0, 1])
print(p.predict(test_input))  # Output: 1

0
1


In [13]:
#OR Single Layer Perceptron

import numpy as np

class Perceptron:
    def __init__(self, N, alpha=0.1):
        self.W =np.random.randn(N+1)/np.sqrt(N)
        self.alpha = alpha
        print("Initial weight : ",self.W)
        
    def step(self, X):
        return 1 if X > 0 else 0
    
    def fit(self, X, y , epochs = 10):
        X=np.c_[X, np.ones((X.shape[0]))]
        
        for epoch in np.arange(0, epochs):
            for (x, target) in zip(X,y):
                p=self.step(np.dot(x, self.W))
                if p!=target:
                    error=p-target
                    self.W += - self.alpha * error * x
                    print(self.W)
                    
    def predict(self, X, addBias=True):
        X = np.atleast_2d(X)
        if addBias:
            X = np.c_[X, np.ones((X.shape[0]))]
        return self.step(np.dot(X, self.W))

import numpy as np
# construct the OR dataset
X = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
y = np.array([[0], [1], [1], [1]])
# define our perceptron and train it
print("[INFO] training perceptron...")
p = Perceptron(X.shape[1], alpha=0.1)
p.fit(X, y, epochs=20)

print("[INFO] testing perceptron...")
# now that our network is trained, loop over the data points
for (x, target) in zip(X, y):
    pred = p.predict(x)
    print("[INFO] data={}, ground-truth={}, pred={}".format(x, target[0], pred))

print(p.W)

[INFO] training perceptron...
Initial weight :  [-0.38387214  0.8767539  -0.93844945]
[-0.38387214  0.9767539  -0.83844945]
[-0.28387214  0.9767539  -0.73844945]
[-0.18387214  1.0767539  -0.63844945]
[-0.08387214  1.0767539  -0.53844945]
[ 0.01612786  1.0767539  -0.43844945]
[ 0.11612786  1.0767539  -0.33844945]
[ 0.21612786  1.0767539  -0.23844945]
[ 0.31612786  1.0767539  -0.13844945]
[INFO] testing perceptron...
[INFO] data=[0 0], ground-truth=0, pred=0
[INFO] data=[0 1], ground-truth=1, pred=1
[INFO] data=[1 0], ground-truth=1, pred=1
[INFO] data=[1 1], ground-truth=1, pred=1
[ 0.31612786  1.0767539  -0.13844945]


In [22]:
#AND Single Layer Perceptron

import numpy as np

class Perceptron:
    def __init__(self, N, alpha=0.1):
        self.W =np.random.randn(N+1)/np.sqrt(N)
        self.alpha = alpha
        print("Initial weight : ",self.W)
        
    def step(self, X):
        return 1 if X > 0 else 0
    
    def fit(self, X, y , epochs = 10):
        X=np.c_[X, np.ones((X.shape[0]))]
        
        for epoch in np.arange(0, epochs):
            for (x, target) in zip(X,y):
                p=self.step(np.dot(x, self.W))
                if p!=target:
                    error=p-target
                    self.W += - self.alpha * error * x
                    
    def predict(self, X, addBias=True):
        X = np.atleast_2d(X)
        if addBias:
            X = np.c_[X, np.ones((X.shape[0]))]
        return self.step(np.dot(X, self.W))

import numpy as np
# construct the AND dataset
X = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
y = np.array([[0], [0], [0], [1]])
# define our perceptron and train it
print("[INFO] training perceptron...")
p = Perceptron(X.shape[1], alpha=0.1)
p.fit(X, y, epochs=20)

print("[INFO] testing perceptron...")
# now that our network is trained, loop over the data points
for (x, target) in zip(X, y):
    pred = p.predict(x)
    print("[INFO] data={}, ground-truth={}, pred={}".format(x, target[0], pred))

print(p.W)

[INFO] training perceptron...
Initial weight :  [ 0.2614561  -0.14183586  0.47789266]
[INFO] testing perceptron...
[INFO] data=[0 0], ground-truth=0, pred=0
[INFO] data=[0 1], ground-truth=0, pred=0
[INFO] data=[1 0], ground-truth=0, pred=0
[INFO] data=[1 1], ground-truth=1, pred=1
[ 0.2614561   0.15816414 -0.32210734]


In [12]:
#XOR MultiLayer Perceptron

import numpy as np

def sigmoid(x):
	return 1.0/(1.0 + np.exp(-x))

def sigmoid_der(x):
	return x*(1.0 - x)

class NN:
    def __init__(self, inputs):
        self.inputs = inputs
        self.l=len(self.inputs)
        self.li=len(self.inputs[0])

        self.wi=np.random.random((self.li, self.l))
        self.wh=np.random.random((self.l, 1))

    def think(self, inp):
        s1=sigmoid(np.dot(inp, self.wi))
        s2=sigmoid(np.dot(s1, self.wh))
        return s2

    def train(self, inputs,outputs, it):
        for i in range(it):
            l0=inputs
            l1=sigmoid(np.dot(l0, self.wi))
            l2=sigmoid(np.dot(l1, self.wh))

            l2_err=outputs - l2
            l2_delta = np.multiply(l2_err, sigmoid_der(l2))

            l1_err=np.dot(l2_delta, self.wh.T)
            l1_delta=np.multiply(l1_err, sigmoid_der(l1))

            self.wh+=np.dot(l1.T, l2_delta)
            self.wi+=np.dot(l0.T, l1_delta)

inputs=np.array([[0,0], [0,1], [1,0], [1,1] ])
outputs=np.array([ [0], [1],[1],[0] ])

n=NN(inputs)
print("Before Training")
print(n.think(inputs))
n.train(inputs, outputs, 100000)
print("After Training")
print(n.think(inputs))

Before Training
[[0.71036995]
 [0.78052813]
 [0.76765639]
 [0.81521148]]
After Training
[[0.0041092 ]
 [0.99528109]
 [0.99528737]
 [0.00481049]]


In [54]:
#3) Single Layer Perceptron for given weights
import numpy as np

class Perceptron:
    def __init__(self, N, alpha=0.1):
        self.W =[.75,.5,-.6]
        self.alpha = alpha
        print("Initial weight : ",self.W)
        
    def step(self, X):
        return 1 if X >= 0 else -1
    
    def fit(self, X, y , epochs = 10):
        X=np.c_[np.ones((X.shape[0])), X]
        
        for epoch in np.arange(0, epochs):
            for (x, target) in zip(X,y):
                p=self.step(np.dot(x, self.W))
                if p!=target:
                    error=p-target
                    self.W += - self.alpha * error * x
                    print(self.W)
                    
    def predict(self, X, addBias=True):
        X = np.atleast_2d(X)
        if addBias:
            X = np.c_[np.ones((X.shape[0])), X]
        return self.step(np.dot(X, self.W))

import numpy as np
# construct the OR dataset
X = np.array([[7, 7], [2.8, 0.8], [1.2, 3], [7.8, 6.1]])
y = np.array([[-1], [1], [1], [-1]])
# define our perceptron and train it
print("[INFO] training perceptron...")
p = Perceptron(X.shape[1], alpha=0.2)
p.fit(X, y, epochs=4)

print("[INFO] testing perceptron...")
# now that our network is trained, loop over the data points
for (x, target) in zip(X, y):
    pred = p.predict(x)
    print("[INFO] data={}, ground-truth={}, pred={}".format(x, target[0],pred))

print(p.W)

[INFO] training perceptron...
Initial weight :  [0.75, 0.5, -0.6]
[ 0.35 -2.3  -3.4 ]
[ 0.75 -1.18 -3.08]
[ 1.15 -0.7  -1.88]
[ 1.55  0.42 -1.56]
[ 1.95  0.9  -0.36]
[ 1.55 -2.22 -2.8 ]
[ 1.95 -1.1  -2.48]
[ 2.35 -0.62 -1.28]
[ 2.75  0.5  -0.96]
[ 2.35 -2.62 -3.4 ]
[INFO] testing perceptron...
[INFO] data=[7. 7.], ground-truth=-1, pred=-1
[INFO] data=[2.8 0.8], ground-truth=1, pred=-1
[INFO] data=[1.2 3. ], ground-truth=1, pred=-1
[INFO] data=[7.8 6.1], ground-truth=-1, pred=-1
[ 2.35 -2.62 -3.4 ]


In [34]:
#5) Single Layer Perceptron for given weights

import numpy as np

class Perceptron:
    def __init__(self, N, alpha=0.1):
        self.W =[-0.2,0.2,0.3]
        self.alpha = alpha
        print("Initial weight : ",self.W)
        
    def step(self, X):
        return 1 if X > 0 else 0
    
    def fit(self, X, y , epochs = 10):
        X=np.c_[np.ones((X.shape[0])), X]
        #print(X)
        for epoch in np.arange(0, epochs):
            for (x, target) in zip(X,y):
                p=self.step(np.dot(x, self.W))
                print(p, target)
                if p!=target:
                    error=p-target
                    self.W += - self.alpha * error * x
                print(self.W)
                    
    def predict(self, X, addBias=True):
        X = np.atleast_2d(X)
        if addBias:
            X = np.c_[np.ones((X.shape[0])), X]
        return self.step(np.dot(X, self.W))

import numpy as np
# construct the OR dataset
X = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
y = np.array([[0], [1], [1], [1]])
# define our perceptron and train it
print("[INFO] training perceptron...")
p = Perceptron(X.shape[1], alpha=0.1)
p.fit(X, y, epochs=2)

print("[INFO] testing perceptron...")
# now that our network is trained, loop over the data points
for (x, target) in zip(X, y):
    pred = p.predict(x)
    print("[INFO] data={}, ground-truth={}, pred={}".format(x, target[0], pred))

print(p.W)

[INFO] training perceptron...
Initial weight :  [-0.2, 0.2, 0.3]
0 [0]
[-0.2, 0.2, 0.3]
1 [1]
[-0.2, 0.2, 0.3]
0 [1]
[-0.1  0.3  0.3]
1 [1]
[-0.1  0.3  0.3]
0 [0]
[-0.1  0.3  0.3]
1 [1]
[-0.1  0.3  0.3]
1 [1]
[-0.1  0.3  0.3]
1 [1]
[-0.1  0.3  0.3]
[INFO] testing perceptron...
[INFO] data=[0 0], ground-truth=0, pred=0
[INFO] data=[0 1], ground-truth=1, pred=1
[INFO] data=[1 0], ground-truth=1, pred=1
[INFO] data=[1 1], ground-truth=1, pred=1
[-0.1  0.3  0.3]


In [49]:
#4b bias -0.5

#OR Single Layer Perceptron

import numpy as np

class Perceptron:
    def __init__(self, N, alpha=0.1):
        self.W =[-0.5,1,1]
        self.alpha = alpha
        print("Initial weight : ",self.W)
        
    def step(self, X):
        return 1 if X > 0 else 0
    
    def fit(self, X, y , epochs = 10):
        X=np.c_[np.ones((X.shape[0])), X]
        
        for epoch in np.arange(0, epochs):
            for (x, target) in zip(X,y):
                p=self.step(np.dot(x, self.W))
                if p!=target:
                    error=p-target
                    self.W += - self.alpha * error * x
                    print(self.W)
                    
    def predict(self, X, addBias=True):
        X = np.atleast_2d(X)
        if addBias:
            X = np.c_[np.ones((X.shape[0])), X]
        print(np.dot(X, self.W))
        return self.step(np.dot(X, self.W))

import numpy as np
# construct the OR dataset
X = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
y = np.array([[0], [1], [1], [1]])
# define our perceptron and train it
print("[INFO] training perceptron...")
p = Perceptron(X.shape[1], alpha=0.1)
p.fit(X, y, epochs=20)

print("[INFO] testing perceptron...")
# now that our network is trained, loop over the data points
for (x, target) in zip(X, y):
    pred = p.predict(x)
    print("[INFO] data={}, ground-truth={}, pred={}".format(x, target[0], pred))

print(p.W)

[INFO] training perceptron...
Initial weight :  [-0.5, 1, 1]
[INFO] testing perceptron...
[-0.5]
[INFO] data=[0 0], ground-truth=0, pred=0
[0.5]
[INFO] data=[0 1], ground-truth=1, pred=1
[0.5]
[INFO] data=[1 0], ground-truth=1, pred=1
[1.5]
[INFO] data=[1 1], ground-truth=1, pred=1
[-0.5, 1, 1]


In [52]:
#4a bias -1.5

import numpy as np

class Perceptron:
    def __init__(self, N, alpha=0.1):
        self.W =[-1.5,1,1]
        self.alpha = alpha
        print("Initial weight : ",self.W)
        
    def step(self, X):
        return 1 if X > 0 else 0
    
    def fit(self, X, y , epochs = 10):
        X=np.c_[np.ones((X.shape[0])), X]
        
        for epoch in np.arange(0, epochs):
            for (x, target) in zip(X,y):
                p=self.step(np.dot(x, self.W))
                if p!=target:
                    error=p-target
                    self.W += - self.alpha * error * x
                    
    def predict(self, X, addBias=True):
        X = np.atleast_2d(X)
        if addBias:
            X = np.c_[np.ones((X.shape[0])), X]
        print(np.dot(X, self.W))
        return self.step(np.dot(X, self.W))

import numpy as np
# construct the AND dataset
X = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
y = np.array([[0], [0], [0], [1]])
# define our perceptron and train it
print("[INFO] training perceptron...")
p = Perceptron(X.shape[1], alpha=0.1)
#p.fit(X, y, epochs=20)

print("[INFO] testing perceptron...")
# now that our network is trained, loop over the data points
for (x, target) in zip(X, y):
    pred = p.predict(x)
    print("[INFO] data={}, ground-truth={}, pred={}".format(x, target[0], pred))

print(p.W)

[INFO] training perceptron...
Initial weight :  [-1.5, 1, 1]
[INFO] testing perceptron...
[-1.5]
[INFO] data=[0 0], ground-truth=0, pred=0
[-0.5]
[INFO] data=[0 1], ground-truth=0, pred=0
[-0.5]
[INFO] data=[1 0], ground-truth=0, pred=0
[0.5]
[INFO] data=[1 1], ground-truth=1, pred=1
[-1.5, 1, 1]


In [76]:
#6)

#XORMultiLayer Perceptron

import numpy as np

def sigmoid(x):
	return 1.0/(1.0 + np.exp(-x))

def sigmoid_der(x):
	return x*(1.0 - x)

class NN:
    def __init__(self, inputs):
        self.inputs = inputs
        self.l=len(self.inputs)
        self.li=len(self.inputs[0])

        self.wi=[0.5,0.7,0.6,1,1,1]
        self.wh=[-0.5,-1,1]

    def think(self, inp):
        s1=sigmoid(np.dot(inp, self.wi))
        s2=sigmoid(np.dot(s1, self.wh))
        return s2

    def train(self, inputs, it):
        for i in range(it):
            l0=np.c_[np.ones((inputs.shape[0])), inputs]
            l1=sigmoid(np.dot(l0, self.wi[0:3]))
            l2=sigmoid(np.dot(l0, self.wi[3:6]))
            l3=[1,l1[0],l2[0]]
            print(l3)
            print(np.dot(l3, self.wh))
            l4 = sigmoid(np.dot(l3, self.wh))
            print("a1 = ",l1,"a2 = ",l2,"Output = ",l4)
            if(l4<=0.5):
                print("Class: 0")
            else:
                print("Class: 1")

inputs=np.array([[0,0]])
#outputs=np.array([ [0], [1],[1],[0] ])

n=NN(inputs)
n.train(inputs,1)

inputs=np.array([[1,1]])
#outputs=np.array([ [0], [1],[1],[0] ])

n=NN(inputs)
n.train(inputs,1)

[1, 0.6224593312018546, 0.7310585786300049]
-0.3914007525718496
a1 =  [0.62245933] a2 =  [0.73105858] Output =  0.4033801435652353
Class: 0
[1, 0.8581489350995123, 0.9525741268224334]
-0.40557480827707904
a1 =  [0.85814894] a2 =  [0.95257413] Output =  0.39997367224830277
Class: 0
