In [ ]:
import numpy as np

In [60]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_derivative(x):
    return x * (1 - x)

weights_input_hidden = np.array([[0.15, 0.25],[0.20, 0.30]])
weights_hidden_output = np.array([[0.40, 0.45],[0.50, 0.55]])

bias_hidden = np.array([0.35, 0.35])
bias_output = np.array([0.60, 0.60])

X = np.array([[0.05, 0.10]])

y = np.array([[0.01, 0.99]])

learning_rate = 0.5
epochs = 4000

for epoch in range(epochs):
    
    # Forward propagation
    hidden_layer_input = np.dot(X, weights_input_hidden) + bias_hidden
    hidden_layer_output = sigmoid(hidden_layer_input)

    output_layer_input = np.dot(hidden_layer_output, weights_hidden_output) + bias_output
    output_layer_output = sigmoid(output_layer_input)
    
    print("First Pass Output: ", output_layer_output)
    
    # Backpropagation
    error = y - output_layer_output
    
    output_delta = error * sigmoid_derivative(output_layer_output)
    print("Error: ", error)

    hidden_error = output_delta.dot(weights_hidden_output.T)
    hidden_delta = hidden_error * sigmoid_derivative(hidden_layer_output)

    weights_hidden_output += hidden_layer_output.T.dot(output_delta) * learning_rate
    weights_input_hidden += X.T.dot(hidden_delta) * learning_rate
    bias_output += np.sum(output_delta, axis=0) * learning_rate
    bias_hidden += np.sum(hidden_delta, axis=0) * learning_rate
    
    print("Updated weights")
    print(weights_hidden_output)
    print(weights_input_hidden)

First Pass Output:  [[0.75689851 0.76768012]]
Error:  [[-0.74689851  0.22231988]]
Updated weights
[[0.35923295 0.46176163]
 [0.45898459 0.56183328]]
[[0.14977601 0.24971783]
 [0.19955202 0.29943566]]
First Pass Output:  [[0.73445459 0.77344125]]
Error:  [[-0.72445459  0.21655875]]
Updated weights
[[0.31739841 0.47299743]
 [0.41691453 0.57313233]]
[[0.14957536 0.24945569]
 [0.19915072 0.29891139]]
First Pass Output:  [[0.71013203 0.7788546 ]]
Error:  [[-0.70013203  0.2111454 ]]
Updated weights
[[0.2747975  0.4837476 ]
 [0.37409485 0.58393772]]
[[0.14940291 0.24921915]
 [0.19880582 0.29843829]]
First Pass Output:  [[0.68409858 0.78395772]]
Error:  [[-0.67409858  0.20604228]]
Updated weights
[[0.23179709 0.4940483 ]
 [0.33089596 0.59428596]]
[[0.14926295 0.24901329]
 [0.19852589 0.29802657]]
First Pass Output:  [[0.65663528 0.78878395]]
Error:  [[-0.64663528  0.20121605]]
Updated weights
[[0.18881242 0.50393205]
 [0.28773605 0.60421001]]
[[0.14915871 0.24884229]
 [0.19831741 0.29768457]]


[[0.16270812 0.26118742]
 [0.22541625 0.32237485]]
First Pass Output:  [[0.06493928 0.94061853]]
Error:  [[-0.05493928  0.04938147]]
Updated weights
[[-0.90395275  0.96609257]
 [-0.80253781  1.06475854]]
[[0.16274024 0.26121932]
 [0.22548048 0.32243864]]
First Pass Output:  [[0.06473699 0.94077749]]
Error:  [[-0.05473699  0.04922251]]
Updated weights
[[-0.90503602  0.96698899]
 [-0.80361514  1.06565004]]
[[0.16277219 0.26125105]
 [0.22554438 0.3225021 ]]
First Pass Output:  [[0.06453653 0.9409352 ]]
Error:  [[-0.05453653  0.0490648 ]]
Updated weights
[[-0.90611245  0.9678805 ]
 [-0.80468567  1.06653666]]
[[0.16280397 0.26128261]
 [0.22560794 0.32256522]]
First Pass Output:  [[0.06433788 0.94109167]]
Error:  [[-0.05433788  0.04890833]]
Updated weights
[[-0.90718213  0.96876716]
 [-0.80574949  1.06741846]]
[[0.16283558 0.26131401]
 [0.22567116 0.32262802]]
First Pass Output:  [[0.06414102 0.94124691]]
Error:  [[-0.05414102  0.04875309]]
Updated weights
[[-0.90824513  0.96964901]
 [-0.806

Error:  [[-0.03287951  0.0309525 ]]
Updated weights
[[-1.04523189  1.08858905]
 [-0.94305435  1.18659399]]
[[0.16716829 0.26563082]
 [0.23433659 0.33126164]]
First Pass Output:  [[0.04282139 0.95909889]]
Error:  [[-0.03282139  0.03090111]]
Updated weights
[[-1.04568507  1.0889974 ]
 [-0.94350514  1.18700018]]
[[0.16718327 0.26564578]
 [0.23436655 0.33129156]]
First Pass Output:  [[0.04276352 0.95915007]]
Error:  [[-0.03276352  0.03084993]]
Updated weights
[[-1.04613691  1.08940463]
 [-0.9439546   1.18740526]]
[[0.16719821 0.2656607 ]
 [0.23439642 0.3313214 ]]
First Pass Output:  [[0.04270588 0.95920105]]
Error:  [[-0.03270588  0.03079895]]
Updated weights
[[-1.04658743  1.08981074]
 [-0.94440274  1.18780923]]
[[0.16721311 0.26567558]
 [0.23442622 0.33135116]]
First Pass Output:  [[0.04264849 0.95925184]]
Error:  [[-0.03264849  0.03074816]]
Updated weights
[[-1.04703662  1.09021574]
 [-0.94484956  1.18821209]]
[[0.16722797 0.26569042]
 [0.23445594 0.33138084]]
First Pass Output:  [[0.04

 [-1.01585676  1.25315401]]
[[0.16964184 0.26810331]
 [0.23928368 0.33620663]]
First Pass Output:  [[0.03435134 0.96673431]]
Error:  [[-0.02435134  0.02326569]]
Updated weights
[[-1.11869115  1.1557529 ]
 [-1.01613187  1.25340883]]
[[0.16965138 0.26811286]
 [0.23930276 0.33622572]]
First Pass Output:  [[0.0343225  0.96676079]]
Error:  [[-0.0243225   0.02323921]]
Updated weights
[[-1.11896714  1.15600856]
 [-1.01640644  1.25366318]]
[[0.16966091 0.26812239]
 [0.23932181 0.33624478]]
First Pass Output:  [[0.03429373 0.96678721]]
Error:  [[-0.02429373  0.02321279]]
Updated weights
[[-1.11924259  1.15626375]
 [-1.01668049  1.25391706]]
[[0.16967041 0.2681319 ]
 [0.23934083 0.3362638 ]]
First Pass Output:  [[0.03426504 0.96681355]]
Error:  [[-0.02426504  0.02318645]]
Updated weights
[[-1.11951751  1.15651846]
 [-1.01695401  1.25417048]]
[[0.16967991 0.2681414 ]
 [0.23935981 0.33628279]]
First Pass Output:  [[0.03423643 0.96683983]]
Error:  [[-0.02423643  0.02316017]]
Updated weights
[[-1.11

First Pass Output:  [[0.02968129 0.97106223]]
Error:  [[-0.01968129  0.01893777]]
Updated weights
[[-1.16645917  1.20031155]
 [-1.06365878  1.29774258]]
[[0.17131977 0.26978258]
 [0.24263955 0.33956516]]
First Pass Output:  [[0.02966343 0.97107893]]
Error:  [[-0.01966343  0.01892107]]
Updated weights
[[-1.16665498  1.2004954 ]
 [-1.06385361  1.29792551]]
[[0.17132669 0.2697895 ]
 [0.24265338 0.33957901]]
First Pass Output:  [[0.02964561 0.9710956 ]]
Error:  [[-0.01964561  0.0189044 ]]
Updated weights
[[-1.16685051  1.20067899]
 [-1.06404817  1.29810819]]
[[0.1713336  0.26979642]
 [0.2426672  0.33959284]]
First Pass Output:  [[0.02962782 0.97111224]]
Error:  [[-0.01962782  0.01888776]]
Updated weights
[[-1.16704576  1.20086233]
 [-1.06424245  1.29829061]]
[[0.1713405  0.26980333]
 [0.24268099 0.33960665]]
First Pass Output:  [[0.02961007 0.97112884]]
Error:  [[-0.01961007  0.01887116]]
Updated weights
[[-1.16724073  1.2010454 ]
 [-1.06443644  1.29847277]]
[[0.17134739 0.26981022]
 [0.24

Updated weights
[[-1.2060011   1.23760788]
 [-1.10300579  1.33485507]]
[[0.17272843 0.27119331]
 [0.24545687 0.34238661]]
First Pass Output:  [[0.02626014 0.97428129]]
Error:  [[-0.01626014  0.01571871]]
Updated weights
[[-1.2061462   1.23774534]
 [-1.10315019  1.33499186]]
[[0.17273364 0.27119853]
 [0.24546729 0.34239705]]
First Pass Output:  [[0.02624836 0.97429245]]
Error:  [[-0.01624836  0.01570755]]
Updated weights
[[-1.20629115  1.23788265]
 [-1.10329443  1.33512849]]
[[0.17273885 0.27120374]
 [0.2454777  0.34240748]]
First Pass Output:  [[0.02623659 0.97430359]]
Error:  [[-0.01623659  0.01569641]]
Updated weights
[[-1.20643592  1.2380198 ]
 [-1.1034385   1.33526498]]
[[0.17274405 0.27120895]
 [0.2454881  0.3424179 ]]
First Pass Output:  [[0.02622484 0.97431471]]
Error:  [[-0.01622484  0.01568529]]
Updated weights
[[-1.20658054  1.23815681]
 [-1.10358241  1.33540132]]
[[0.17274925 0.27121416]
 [0.24549849 0.34242831]]
First Pass Output:  [[0.02621311 0.97432582]]
Error:  [[-0.016

Updated weights
[[-1.23190871  1.26221151]
 [-1.1287881   1.3593397 ]]
[[0.17366345 0.27213009]
 [0.24732689 0.34426018]]
First Pass Output:  [[0.02423273 0.97620692]]
Error:  [[-0.01423273  0.01379308]]
Updated weights
[[-1.23202683  1.26232396]
 [-1.12890565  1.3594516 ]]
[[0.17366773 0.27213438]
 [0.24733546 0.34426876]]
First Pass Output:  [[0.02422383 0.97621539]]
Error:  [[-0.01422383  0.01378461]]
Updated weights
[[-1.23214483  1.2624363 ]
 [-1.12902309  1.3595634 ]]
[[0.17367201 0.27213867]
 [0.24734402 0.34427734]]
First Pass Output:  [[0.02421495 0.97622386]]
Error:  [[-0.01421495  0.01377614]]
Updated weights
[[-1.23226273  1.26254853]
 [-1.12914042  1.3596751 ]]
[[0.17367629 0.27214295]
 [0.24735257 0.34428591]]
First Pass Output:  [[0.02420607 0.97623232]]
Error:  [[-0.01420607  0.01376768]]
Updated weights
[[-1.23238051  1.26266066]
 [-1.12925764  1.35978669]]
[[0.17368056 0.27214723]
 [0.24736111 0.34429447]]
First Pass Output:  [[0.02419721 0.97624076]]
Error:  [[-0.014

Error:  [[-0.0126072  0.0122401]]
Updated weights
[[-1.25429846  1.28356576]
 [-1.15107113  1.38059216]]
[[0.17447849 0.27294689]
 [0.24895698 0.34589379]]
First Pass Output:  [[0.02260027 0.97776654]]
Error:  [[-0.01260027  0.01223346]]
Updated weights
[[-1.25439662  1.28365956]
 [-1.15116883  1.38068552]]
[[0.17448208 0.27295049]
 [0.24896416 0.34590098]]
First Pass Output:  [[0.02259334 0.97777317]]
Error:  [[-0.01259334  0.01222683]]
Updated weights
[[-1.25449471  1.28375328]
 [-1.15126645  1.3807788 ]]
[[0.17448566 0.27295408]
 [0.24897132 0.34590816]]
First Pass Output:  [[0.02258643 0.9777798 ]]
Error:  [[-0.01258643  0.0122202 ]]
Updated weights
[[-1.25459272  1.28384693]
 [-1.151364    1.38087201]]
[[0.17448924 0.27295767]
 [0.24897849 0.34591534]]
First Pass Output:  [[0.02257952 0.97778641]]
Error:  [[-0.01257952  0.01221359]]
Updated weights
[[-1.25469065  1.2839405 ]
 [-1.15146146  1.38096513]]
[[0.17449282 0.27296126]
 [0.24898564 0.34592252]]
First Pass Output:  [[0.0225

 [0.25025079 0.34719065]]
First Pass Output:  [[0.0213869  0.97893078]]
Error:  [[-0.0113869   0.01106922]]
Updated weights
[[-1.27203733  1.30053746]
 [-1.1687265   1.39748398]]
[[0.17512849 0.27359844]
 [0.25025699 0.34719687]]
First Pass Output:  [[0.02138125 0.97893621]]
Error:  [[-0.01138125  0.01106379]]
Updated weights
[[-1.27212165  1.30061824]
 [-1.16881043  1.39756438]]
[[0.17513159 0.27360154]
 [0.25026319 0.34720308]]
First Pass Output:  [[0.02137561 0.97894164]]
Error:  [[-0.01137561  0.01105836]]
Updated weights
[[-1.2722059   1.30069896]
 [-1.16889429  1.39764472]]
[[0.17513469 0.27360464]
 [0.25026938 0.34720929]]
First Pass Output:  [[0.02136997 0.97894706]]
Error:  [[-0.01136997  0.01105294]]
Updated weights
[[-1.2722901   1.30077961]
 [-1.16897809  1.397725  ]]
[[0.17513778 0.27360775]
 [0.25027557 0.34721549]]
First Pass Output:  [[0.02136434 0.97895247]]
Error:  [[-0.01136434  0.01104753]]
Updated weights
[[-1.27237423  1.30086022]
 [-1.16906183  1.39780522]]
[[0.1

 [0.25144242 0.34838529]]
First Pass Output:  [[0.02032948 0.97994871]]
Error:  [[-0.01032948  0.01005129]]
Updated weights
[[-1.28820282  1.31604052]
 [-1.18481672  1.41291485]]
[[0.17572391 0.27419535]
 [0.25144782 0.34839071]]
First Pass Output:  [[0.02032481 0.97995321]]
Error:  [[-0.01032481  0.01004679]]
Updated weights
[[-1.28827587  1.31611064]
 [-1.18488943  1.41298465]]
[[0.17572661 0.27419806]
 [0.25145321 0.34839611]]
First Pass Output:  [[0.02032015 0.9799577 ]]
Error:  [[-0.01032015  0.0100423 ]]
Updated weights
[[-1.28834887  1.31618073]
 [-1.18496209  1.4130544 ]]
[[0.1757293  0.27420076]
 [0.2514586  0.34840152]]
First Pass Output:  [[0.0203155  0.97996219]]
Error:  [[-0.0103155   0.01003781]]
Updated weights
[[-1.28842182  1.31625076]
 [-1.1850347   1.41312412]]
[[0.175732   0.27420346]
 [0.25146399 0.34840692]]
First Pass Output:  [[0.02031085 0.97996667]]
Error:  [[-0.01031085  0.01003333]]
Updated weights
[[-1.28849472  1.31632075]
 [-1.18510727  1.41319378]]
[[0.1

 [-1.1986632   1.42621914]]
[[0.17623847 0.27471128]
 [0.25247695 0.34942256]]
First Pass Output:  [[0.01945557 0.98079222]]
Error:  [[-0.00945557  0.00920778]]
Updated weights
[[-1.30217773  1.32946826]
 [-1.19872719  1.42628067]]
[[0.17624086 0.27471367]
 [0.25248171 0.34942734]]
First Pass Output:  [[0.01945163 0.98079602]]
Error:  [[-0.00945163  0.00920398]]
Updated weights
[[-1.30224198  1.32953004]
 [-1.19879114  1.42634217]]
[[0.17624324 0.27471606]
 [0.25248648 0.34943211]]
First Pass Output:  [[0.0194477  0.98079982]]
Error:  [[-0.0094477   0.00920018]]
Updated weights
[[-1.30230618  1.32959179]
 [-1.19885506  1.42640364]]
[[0.17624562 0.27471844]
 [0.25249123 0.34943689]]
First Pass Output:  [[0.01944378 0.98080361]]
Error:  [[-0.00944378  0.00919639]]
Updated weights
[[-1.30237035  1.3296535 ]
 [-1.19891893  1.42646506]]
[[0.176248   0.27472083]
 [0.25249599 0.34944166]]
First Pass Output:  [[0.01943985 0.98080741]]
Error:  [[-0.00943985  0.00919259]]
Updated weights
[[-1.30

First Pass Output:  [[0.01863895 0.98158219]]
Error:  [[-0.00863895  0.00841781]]
Updated weights
[[-1.31578754  1.34256583]
 [-1.21227482  1.4393184 ]]
[[0.17674616 0.27522037]
 [0.25349232 0.35044074]]
First Pass Output:  [[0.01863563 0.9815854 ]]
Error:  [[-0.00863563  0.0084146 ]]
Updated weights
[[-1.31584399  1.34262019]
 [-1.21233101  1.43937252]]
[[0.17674826 0.27522247]
 [0.25349652 0.35044495]]
First Pass Output:  [[0.01863231 0.98158861]]
Error:  [[-0.00863231  0.00841139]]
Updated weights
[[-1.31590041  1.34267453]
 [-1.21238717  1.4394266 ]]
[[0.17675036 0.27522458]
 [0.25350072 0.35044916]]
First Pass Output:  [[0.018629   0.98159182]]
Error:  [[-0.008629    0.00840818]]
Updated weights
[[-1.3159568   1.34272883]
 [-1.2124433   1.43948066]]
[[0.17675246 0.27522668]
 [0.25350491 0.35045336]]
First Pass Output:  [[0.01862569 0.98159503]]
Error:  [[-0.00862569  0.00840497]]
Updated weights
[[-1.31601316  1.34278311]
 [-1.21249941  1.43953469]]
[[0.17675455 0.27522878]
 [0.25

First Pass Output:  [[0.01790228 0.9822962 ]]
Error:  [[-0.00790228  0.0077038 ]]
Updated weights
[[-1.32856159  1.35487588]
 [-1.22499101  1.45157269]]
[[0.17722201 0.27569758]
 [0.25444402 0.35139517]]
First Pass Output:  [[0.01789947 0.98229893]]
Error:  [[-0.00789947  0.00770107]]
Updated weights
[[-1.32861136  1.35492387]
 [-1.22504055  1.45162047]]
[[0.17722387 0.27569945]
 [0.25444774 0.35139889]]
First Pass Output:  [[0.01789666 0.98230166]]
Error:  [[-0.00789666  0.00769834]]
Updated weights
[[-1.3286611   1.35497184]
 [-1.22509008  1.45166822]]
[[0.17722573 0.27570131]
 [0.25445145 0.35140261]]
First Pass Output:  [[0.01789384 0.98230439]]
Error:  [[-0.00789384  0.00769561]]
Updated weights
[[-1.32871082  1.35501978]
 [-1.22513957  1.45171595]]
[[0.17722758 0.27570317]
 [0.25445516 0.35140633]]
First Pass Output:  [[0.01789103 0.98230712]]
Error:  [[-0.00789103  0.00769288]]
Updated weights
[[-1.32876052  1.3550677 ]
 [-1.22518905  1.45176366]]
[[0.17722943 0.27570503]
 [0.25

First Pass Output:  [[0.01740828 0.98277573]]
Error:  [[-0.00740828  0.00722427]]
Updated weights
[[-1.33741211  1.3634136 ]
 [-1.23380174  1.46007204]]
[[0.17755256 0.2760291 ]
 [0.25510512 0.3520582 ]]
First Pass Output:  [[0.01740577 0.98277817]]
Error:  [[-0.00740577  0.00722183]]
Updated weights
[[-1.33745759  1.3634575 ]
 [-1.23384701  1.46011573]]
[[0.17755426 0.27603081]
 [0.25510852 0.35206161]]
First Pass Output:  [[0.01740327 0.9827806 ]]
Error:  [[-0.00740327  0.0072194 ]]
Updated weights
[[-1.33750305  1.36350137]
 [-1.23389227  1.46015941]]
[[0.17755596 0.27603251]
 [0.25511192 0.35206502]]
First Pass Output:  [[0.01740077 0.98278303]]
Error:  [[-0.00740077  0.00721697]]
Updated weights
[[-1.33754849  1.36354522]
 [-1.23393751  1.46020306]]
[[0.17755766 0.27603421]
 [0.25511532 0.35206843]]
First Pass Output:  [[0.01739827 0.98278545]]
Error:  [[-0.00739827  0.00721455]]
Updated weights
[[-1.33759391  1.36358905]
 [-1.23398272  1.46024669]]
[[0.17755936 0.27603592]
 [0.25

Updated weights
[[-1.34697271  1.37264363]
 [-1.24331963  1.46926083]]
[[0.17791037 0.27638799]
 [0.25582074 0.35277597]]
First Pass Output:  [[0.01688708 0.98328225]]
Error:  [[-0.00688708  0.00671775]]
Updated weights
[[-1.34701386  1.37268336]
 [-1.24336059  1.46930038]]
[[0.17791191 0.27638953]
 [0.25582383 0.35277907]]
First Pass Output:  [[0.01688488 0.98328439]]
Error:  [[-0.00688488  0.00671561]]
Updated weights
[[-1.34705498  1.37272308]
 [-1.24340153  1.46933992]]
[[0.17791345 0.27639108]
 [0.25582691 0.35278216]]
First Pass Output:  [[0.01688268 0.98328653]]
Error:  [[-0.00688268  0.00671347]]
Updated weights
[[-1.34709608  1.37276278]
 [-1.24344245  1.46937945]]
[[0.17791499 0.27639262]
 [0.25582999 0.35278525]]
First Pass Output:  [[0.01688049 0.98328866]]
Error:  [[-0.00688049  0.00671134]]
Updated weights
[[-1.34713717  1.37280246]
 [-1.24348336  1.46941895]]
[[0.17791653 0.27639417]
 [0.25583307 0.35278833]]
First Pass Output:  [[0.01687829 0.9832908 ]]
Error:  [[-0.006

First Pass Output:  [[0.01646647 0.98369145]]
Error:  [[-0.00646647  0.00630855]]
Updated weights
[[-1.35497166  1.38037135]
 [-1.25128306  1.47695423]]
[[0.17821031 0.27668884]
 [0.25642062 0.35337768]]
First Pass Output:  [[0.0164645  0.98369337]]
Error:  [[-0.0064645   0.00630663]]
Updated weights
[[-1.35500939  1.38040781]
 [-1.25132062  1.47699053]]
[[0.17821172 0.27669026]
 [0.25642345 0.35338052]]
First Pass Output:  [[0.01646253 0.98369528]]
Error:  [[-0.00646253  0.00630472]]
Updated weights
[[-1.35504711  1.38044426]
 [-1.25135817  1.47702682]]
[[0.17821314 0.27669168]
 [0.25642628 0.35338336]]
First Pass Output:  [[0.01646056 0.9836972 ]]
Error:  [[-0.00646056  0.0063028 ]]
Updated weights
[[-1.35508481  1.38048069]
 [-1.2513957   1.47706309]]
[[0.17821455 0.2766931 ]
 [0.25642911 0.3533862 ]]
First Pass Output:  [[0.01645859 0.98369911]]
Error:  [[-0.00645859  0.00630089]]
Updated weights
[[-1.35512249  1.38051711]
 [-1.25143322  1.47709934]]
[[0.17821597 0.27669452]
 [0.25

 [-1.25790849  1.4833584 ]]
[[0.17846023 0.27693953]
 [0.25692045 0.35387906]]
First Pass Output:  [[0.01612065 0.98402816]]
Error:  [[-0.00612065  0.00597184]]
Updated weights
[[-1.36166153  1.38683782]
 [-1.25794337  1.48339213]]
[[0.17846154 0.27694085]
 [0.25692308 0.35388171]]
First Pass Output:  [[0.01611886 0.98402991]]
Error:  [[-0.00611886  0.00597009]]
Updated weights
[[-1.36169656  1.38687169]
 [-1.25797824  1.48342585]]
[[0.17846286 0.27694217]
 [0.25692572 0.35388435]]
First Pass Output:  [[0.01611707 0.98403165]]
Error:  [[-0.00611707  0.00596835]]
Updated weights
[[-1.36173157  1.38690554]
 [-1.2580131   1.48345955]]
[[0.17846417 0.27694349]
 [0.25692835 0.35388699]]
First Pass Output:  [[0.01611528 0.98403339]]
Error:  [[-0.00611528  0.00596661]]
Updated weights
[[-1.36176657  1.38693938]
 [-1.25804794  1.48349324]]
[[0.17846549 0.27694481]
 [0.25693098 0.35388962]]
First Pass Output:  [[0.01611349 0.98403514]]
Error:  [[-0.00611349  0.00596486]]
Updated weights
[[-1.36

Error:  [[-0.00578084  0.00564075]]
Updated weights
[[-1.36837045  1.3933256 ]
 [-1.26462278  1.48985138]]
[[0.17871383 0.27719393]
 [0.25742766 0.35438786]]
First Pass Output:  [[0.01577922 0.98436084]]
Error:  [[-0.00577922  0.00563916]]
Updated weights
[[-1.36840289  1.39335698]
 [-1.26465508  1.48988262]]
[[0.17871505 0.27719516]
 [0.2574301  0.35439031]]
First Pass Output:  [[0.01577759 0.98436242]]
Error:  [[-0.00577759  0.00563758]]
Updated weights
[[-1.36843532  1.39338834]
 [-1.26468737  1.48991385]]
[[0.17871627 0.27719638]
 [0.25743254 0.35439276]]
First Pass Output:  [[0.01577597 0.98436401]]
Error:  [[-0.00577597  0.00563599]]
Updated weights
[[-1.36846774  1.3934197 ]
 [-1.26471965  1.48994506]]
[[0.17871749 0.2771976 ]
 [0.25743498 0.35439521]]
First Pass Output:  [[0.01577434 0.98436559]]
Error:  [[-0.00577434  0.00563441]]
Updated weights
[[-1.36850014  1.39345104]
 [-1.26475191  1.48997627]]
[[0.17871871 0.27719883]
 [0.25743742 0.35439765]]
First Pass Output:  [[0.01

 [-1.27123986  1.49625294]]
[[0.17896407 0.27744497]
 [0.25792815 0.35488994]]
First Pass Output:  [[0.01544952 0.9846823 ]]
Error:  [[-0.00544952  0.0053177 ]]
Updated weights
[[-1.37504662  1.39978433]
 [-1.27126973  1.49628184]]
[[0.17896521 0.27744611]
 [0.25793041 0.35489221]]
First Pass Output:  [[0.01544805 0.98468373]]
Error:  [[-0.00544805  0.00531627]]
Updated weights
[[-1.37507661  1.39981335]
 [-1.27129959  1.49631074]]
[[0.17896634 0.27744724]
 [0.25793267 0.35489448]]
First Pass Output:  [[0.01544658 0.98468517]]
Error:  [[-0.00544658  0.00531483]]
Updated weights
[[-1.37510659  1.39984237]
 [-1.27132944  1.49633962]]
[[0.17896746 0.27744837]
 [0.25793493 0.35489675]]
First Pass Output:  [[0.0154451  0.98468661]]
Error:  [[-0.0054451   0.00531339]]
Updated weights
[[-1.37513656  1.39987137]
 [-1.27135928  1.49636849]]
[[0.17896859 0.27744951]
 [0.25793719 0.35489901]]
First Pass Output:  [[0.01544363 0.98468804]]
Error:  [[-0.00544363  0.00531196]]
Updated weights
[[-1.37

Error:  [[-0.00515264  0.00502807]]
Updated weights
[[-1.38114658  1.40568771]
 [-1.27734311  1.50215949]]
[[0.17919516 0.2776768 ]
 [0.25839031 0.35535359]]
First Pass Output:  [[0.0151513  0.98497325]]
Error:  [[-0.0051513   0.00502675]]
Updated weights
[[-1.38117443  1.40571467]
 [-1.27737085  1.50218634]]
[[0.17919621 0.27767785]
 [0.25839242 0.3553557 ]]
First Pass Output:  [[0.01514995 0.98497456]]
Error:  [[-0.00514995  0.00502544]]
Updated weights
[[-1.38120228  1.40574163]
 [-1.27739858  1.50221318]]
[[0.17919726 0.2776789 ]
 [0.25839452 0.35535781]]
First Pass Output:  [[0.01514861 0.98497587]]
Error:  [[-0.00514861  0.00502413]]
Updated weights
[[-1.38123012  1.40576857]
 [-1.27742629  1.50224001]]
[[0.17919831 0.27767996]
 [0.25839662 0.35535992]]
First Pass Output:  [[0.01514727 0.98497717]]
Error:  [[-0.00514727  0.00502283]]
Updated weights
[[-1.38125795  1.40579551]
 [-1.277454    1.50226683]]
[[0.17919936 0.27768101]
 [0.25839872 0.35536202]]
First Pass Output:  [[0.01

In [62]:
# Test the trained network
hidden_layer_input = np.dot(X, weights_input_hidden) + bias_hidden
hidden_layer_output = sigmoid(hidden_layer_input)

output_layer_input = np.dot(hidden_layer_output, weights_hidden_output) + bias_output
output_layer_output = sigmoid(output_layer_input)

print("Output layer output after training:")
print(output_layer_output)

Output layer output after training:
[[0.01507174 0.98505089]]
